[package]
name = "drumbox01"
version = "0.1.0"
authors = ["iain8 <iain@fastmail.com>"]
publish = false

[dependencies]
iron = "0.5.*"
staticfile = "*"
mount = "*"
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.9.0"
